language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python3 setup.py develop
script:
  - py.test --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls
